site_name: Polkadot Wiki
site_description: The Polkadot knowledge base
site_author: 'Web3 Foundation'
site_url: https://wiki.polkadot.network

nav:
 - Home: index.md
 - Build:
   - Home: polkadot/build/index.md
   - Building on Polkadot: polkadot/build/build-with-polkadot.md
   - Cumulus: polkadot/build/cumulus.md
   - Deploy Parachains: polkadot/build/deploy-parachains.md
   - Examples: polkadot/build/examples/index.md
   - Extrinsic Format: polkadot/build/extrinsic-format.md
   - Hackathons: polkadot/build/hackathon.md
   - Networks: polkadot/build/networks.md
   - Parachain Development Kits: polkadot/build/pdk.md
   - Rust Style Guide: polkadot/build/rust-style-guide.md
   - Smart Contracts: polkadot/build/smart-contracts.md
   - Tools: polkadot/build/tools/index.md
 - Learn:
   - Home: polkadot/learn/index.md
   - Architecture: polkadot/learn/architecture.md
   - Bridges: polkadot/learn/bridges/
   - Comparisons:
     - Cosmos: polkadot/learn/comparisons/cosmos.md
     - Ethereum: polkadot/learn/comparisons.md
     - Tezos: polkadot/learn/comparisons.md
   - Consensus: polkadot/learn/consensus.md
   - Cryptography: polkadot/learn/cryptography.md
   - DOT: polkadot/learn/DOT.md
   - FAQ: polkadot/learn/faq.md
   - GRANDPA: polkadot/learn/consensus.md
   - Glossary: glossary.md
   - Governance: polkadot/learn/governance.md
   - ICMP: polkadot/learn/interchain.md
   - Implementations: polkadot/learn/implementations.md
   - Keys: polkadot/learn/keys.md
   - Parachain Slots: polkadot/learn/auction.md
   - Parachains: polkadot/learn/parachains.md
   - Phragmen: polkadot/learn/phragmen.md
   - Polkadot Runtime Environment: polkadot/learn/PRE.md
   - Polkadot UI: polkadot/learn/UI.md
   - Randomness: polkadot/learn/randomness.md
   - Relevant Links: polkadot/learn/relevant-links.md
   - Roadmap: polkadot/learn/roadmap.md
   - SPREE: polkadot/learn/spree.md
   - Security: polkadot/learn/security.md
   - Staking: polkadot/learn/staking.md
 - Run the Network:
   - Home: polkadot/node/index.md
   - Collator: polkadot/node/collator.md
   - Nominator: polkadot/node/nominator.md
   - Validator: polkadot/node/node-operator.md
   - Guides:
     - How to nominate: polkadot/node/guides/how-to-nominate.md
     - How to validate: polkadot/node/guides/how-to-validate.md
     - How to use systemd: polkadot/node/guides/how-to-systemd.md
   - Governance: polkadot/node/governance/index.md
 - Other Languages:
   - Chinese: lang/chinese/index.md
   - Japanese: lang/japanese.md
 - News: news.md

# Configuration for the Material theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: 'PT Sans'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.ico'
  logo: 'img/Polkadot_symbol_color.png'
  feature:
    tabs: false

# Extra css for further customization
extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://research.web3.foundation/en/latest/mathjax-config.js

# Repository that houses the source code for this site. This
# is needed to render the nice GH link on the top right.
repo_name: 'w3f/polkadot-wiki'
repo_url: 'https://github.com/w3f/polkadot-wiki'

# Social links
extra:
  social:
    - type: 'github'
      size: 'lg'
      link: 'https://github.com/paritytech/polkadot'
    - type: 'twitter'
      size: 'lg'
      link: 'https://twitter.com/polkadotnetwork'
    - type: 'medium'
      size: 'lg'
      link: 'https://medium.com/@polkadotnetwork'

footer:
  logo: 'img/Polkadot_Logotype_white.png'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - mdtooltips
