site_name: Polkadot Wiki
site_description: Information on Polkadot
site_author: 'Web3 Foundation'
site_url: https://wiki.polkadot.network

nav:
 - Home: index.md
 - Build:
   - Cumulus: polkadot/build/cumulus.md
   - Home: polkadot/build/index.md
   - Building on Polkadot: polkadot/build/build_with_polkadot.md
   - Deploy Parachains: polkadot/build/deploy_parachains.md
   - Examples: polkadot/build/examples/index.md
   - Extrinsic Format: polkadot/build/extrinsic-format.md
   - Networks: polkadot/build/networks.md
   - Rust Style Guide: polkadot/build/rust-style-guide.md
   - Tools: polkadot/build/tools/index.md
 - Learn:
   - Comparisons: polkadot/learn/comparisons.md
   - Cryptography: polkadot/learn/cryptography.md
   - DOT: polkadot/learn/DOT.md
   - FAQ: polkadot/learn/faq.md
   - Governance: polkadot/learn/governance.md
   - GRANDPA: polkadot/learn/grandpa.md
   - Implementations: polkadot/learn/implementations.md
   - Phragmen: polkadot/learn/phragmen.md
   - Roadmap: polkadot/learn/roadmap.md
   - Security: polkadot/learn/security.md
   - Staking: polkadot/learn/staking.md
   - Terms: polkadot/learn/terms_and_definitions.md
   - Relevant Links: polkadot/learn/relevant_links.md
   - Parachains: polkadot/learn/parachains.md
   - Polkadot Runtime Environment: polkadot/learn/PRE.md
   - Polkadot UI: polkadot/learn/UI.md
 - Run the Network:
   - Home: polkadot/node/index.md
   - Node Operator / Validator: polkadot/node/node_operator.md
   - Nominator: polkadot/node/nominator.md
   - Collator: polkadot/node/collator.md
   - Governance: polkadot/node/governance/index.md
 - Other Languages:
   - Chinese: lang/chinese.md
   - Japanese: lang/japanese.md

# Configuration for the Material theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'grey'
    accent: 'pink'
  font: 
    text: 'PT Sans'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.ico'
  logo: 'img/logo.svg'
  feature:
    tabs: false

# Extra css for further customization 
extra_css:
  - 'stylesheets/extra.css'

# Repository that houses the source code for this site. This
# is needed to render the nice GH link on the top right.
repo_name: 'w3f/polkadot-wiki'
repo_url: 'https://github.com/w3f/polkadot-wiki'

# Social links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/paritytech/polkadot'
    - type: 'twitter'
      link: 'https://twitter.com/polkadotnetwork'
    - type: 'medium'
      link: 'https://medium.com/@polkadotnetwork'

# extra_javascript:
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - mathjax-config.js

markdown_extensions:
#    - mdx_math
     - admonition
     - codehilite:
         guess_lang: false
     - toc:
         permalink: true